### ISSUE TITLE
[js-controller5] km200 läuft unter js-controller 5 bei mir nicht mehr

### ISSUE THREAD

**Issue by m-s-b** [iobroker-community-adapters/ioBroker.km200#106]
Nach dem Update auf js-controller 5.0.2 bricht der Start des Adapters ab:

`km200 Initialization Error:TypeError: Cannot read properties of undefined (reading '_subscribeForeignStates') at subscribeStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7382:21) at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:111 at new Promise (<anonymous>) at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:20 at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:311:77`

**Comment by crusader85** [comment]
bei mir auch. Gleicher Fehler

**Comment by bullydog1984** [comment]
auch leider das selbe Problem

**Comment by EvilEls** [comment]
hier ebenfalls

```
km200.0 | 2023-06-15 11:02:23.268 | warn | Terminated  (ADAPTER_REQUESTED_TERMINATION): km200 Initialization Error:TypeError:  Cannot read properties of undefined (reading '_subscribeForeignStates')     at subscribeStates  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7367:21)     at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:111     at new Promise (<anonymous>)    at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:20     at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:311:77
km200.0 | 2023-06-15 11:02:22.369 | info | km200.0 address: http://192.168.0.50
km200.0 | 2023-06-15 11:02:22.367 | warn | Adapter  will exit in latest 1 sec with code km200 Initialization  Error:TypeError: Cannot read properties of undefined (reading  '_subscribeForeignStates')    at subscribeStates  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7367:21)     at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:111     at new Promise (<anonymous>)    at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:20     at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:311:77!
km200.0 | 2023-06-15 11:02:22.366 | info | Adapter  disconnected and stopped with dostop(km200 Initialization  Error:TypeError: Cannot read properties of undefined (reading  '_subscribeForeignStates')    at subscribeStates  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7367:21)     at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:111     at new Promise (<anonymous>)    at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:20     at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:311:77)  and callback(false)
km200.0 | 2023-06-15 11:02:22.365 | error | km200  Initialization Error:TypeError: Cannot read properties of undefined  (reading '_subscribeForeignStates')    at subscribeStates  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7367:21)     at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:111     at new Promise (<anonymous>)    at  /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:20     at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:311:77
km200.0 | 2023-06-15 11:02:22.267 | info | starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.km200, node: v18.16.0, js-controller: 5.0.3
```

**Comment by EvilEls** [comment]
Wer nicht auf ein Fix warten kann/will,
der ems-esp Adapter (https://github.com/tp1de/ioBroker.ems-esp) kann auch km200

**Comment by SteveWi-291** [comment]
km200 Initialization Error:TypeError: Cannot read properties of undefined (reading '_subscribeForeignStates') at subscribeStates (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:7375:21) at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:111 at new Promise (<anonymous>) at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:830:20 at /opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:311:77

Auch bei mir der Fehler ;)

**Comment by smarthausleben** [comment]
> Wer nicht auf ein Fix warten kann/will, der ems-esp Adapter (https://github.com/tp1de/ioBroker.ems-esp) kann auch km200

oder zurück auf den alten js-controller 4.0.24 gehen:

1. ins iobroker Verzeichnis (auf meine Raspberry `/opt/iobroker`) wechseln, denn aus dem home Verzeichnis funktioniert es natürlich nicht!
2. `npm install iobroker.js-controller@4.0.24`
