### ISSUE TITLE
All objects deleted after update to version 2.0.5

### ISSUE THREAD

**Issue by blackeagle998** [iobroker-community-adapters/ioBroker.km200#121]
Hello,

after updating to version 2.0.5 and js-controller 5.0.7 all objects under KM200 were deleted.
I got only one state back:
km200.0.dhwCircuits.dhw1.actualTemp

Can anyone please help me, why all other states are lost?

**DEBUG Output:**
km200.0 | 2023-07-10 10:56:01.744 | info | Adapter km200 initialization finished with 1 states.
km200.0 | 2023-07-10 10:56:01.617 | info | Slow Interval=6 hours, Slow-List:
km200.0 | 2023-07-10 10:56:01.617 | info | Fast Interval=1 min, Fast-List: dhwCircuits.dhw1.actualTemp
km200.0 | 2023-07-10 10:56:01.616 | info | Interval=15 min, Norm-list:
km200.0 | 2023-07-10 10:56:01.616 | warn | INit getservices error TypeError: Cannot create property '0' on boolean 'false' at /opt/iobroker/node_modules/iobroker.km200/km200.js:455:61 at Array.forEach (<anonymous>) at /opt/iobroker/node_modules/iobroker.km200/km200.js:455:37 at /opt/iobroker/node_modules/iobroker.km200/lib/myAdapter.js:822:53
km200.0 | 2023-07-10 10:56:01.581 | info | Services found: 130
km200.0 | 2023-07-10 10:55:05.360 | info | km200.0 address: http://x.x.x.x
km200.0 | 2023-07-10 10:55:05.359 | info | km200 initialization started...
km200.0 | 2023-07-10 10:55:05.357 | info | debug: km200 received undefined objects and 1 states, with config adresse,blacklist,fastlist,slowlist,interval,fastinterval,slowinterval,deletestates,accesskey,privatepassword,lang,latitude,longitude,adapterConf,loglevel
km200.0 | 2023-07-10 10:55:05.278 | info | starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.km200, node: v16.20.0, js-controller: 5.0.7

**Versions:**  
 - Adapter version: 2.0.5
 - JS-Controller version: 5.0.7
 - Node version: 16.20.0

**Comment by EvilEls** [comment]
Same problem here.

only one state left after upgrade:
`km200.0.dhwCircuits.dhw1.actualTemp` 

```
km200.0 | 2023-07-10 11:40:37.658 | info | Adapter km200 initialization finished with 1 states.
km200.0 | 2023-07-10 11:40:37.512 | silly | States  user redis pmessage  io.km200.0.*/io.km200.0.dhwCircuits.dhw1.actualTemp:{"val":48.4,"ack":true,"ts":1688982037511,"q":0,"from":"system.adapter.km200.0","user":"system.user.admin","lc":1688982037469}
km200.0 | 2023-07-10 11:40:37.483 | info | Slow Interval=6 hours, Slow-List:
km200.0 | 2023-07-10 11:40:37.482 | info | Fast Interval=1 min, Fast-List: dhwCircuits.dhw1.actualTemp
km200.0 | 2023-07-10 11:40:37.482 | info | Interval=15 min, Norm-list:
km200.0 | 2023-07-10 11:40:37.482 | warn | INit  getservices error TypeError: Cannot create property '0' on boolean  'false' at /opt/iobroker/node_modules/iobroker.km200/km200.js:455:61 at  Array.forEach (<anonymous>) at  /opt/iobroker/node_modules/iobroker.km200/km200.js:455:37 at  /opt/iobroker/node_modules/iobroker.km200/lib/myAdapter.js:822:53
km200.0 | 2023-07-10 11:40:37.471 | silly | States  user redis pmessage  io.km200.0.*/io.km200.0.dhwCircuits.dhw1.actualTemp:{"val":48.4,"ack":true,"ts":1688982037469,"q":0,"from":"system.adapter.km200.0","user":"system.user.admin","lc":1688982037469}
km200.0 | 2023-07-10 11:40:37.448 | info | Services found: 121
km200.0 | 2023-07-10 11:39:44.812 | info | km200.0 address: http://192.168.0.50
km200.0 | 2023-07-10 11:39:44.811 | info | km200 initialization started...
km200.0 | 2023-07-10 11:39:44.810 | info | debug:  km200 received undefined objects and 0 states, with config  adresse,blacklist,fastlist,slowlist,interval,fastinterval,slowinterval,deletestates,accesskey,privatepassword,lang,latitude,longitude,adapterConf,loglevel
km200.0 | 2023-07-10 11:39:44.771 | silly | States  system redis pmessage  io.system.adapter.km200.0.logLevel/io.system.adapter.km200.0.logLevel:{"val":"silly","ack":true,"ts":1688981984761,"q":0,"from":"system.adapter.km200.0","lc":1688981864596}
km200.0 | 2023-07-10 11:39:44.732 | info | starting. Version 2.0.5 in /opt/iobroker/node_modules/iobroker.km200, node: v18.16.0, js-controller: 5.0.5
km200.0 | 2023-07-10 11:39:44.659 | silly | statesDB connected
km200.0 | 2023-07-10 11:39:44.658 | debug | States connected to redis: 127.0.0.1:6379
km200.0 | 2023-07-10 11:39:44.653 | debug | States create User PubSub Client
km200.0 | 2023-07-10 11:39:44.652 | debug | States create System PubSub Client
km200.0 | 2023-07-10 11:39:44.648 | debug | Redis States: Use Redis connection: 127.0.0.1:6379
km200.0 | 2023-07-10 11:39:44.647 | silly | objectDB connected
km200.0 | 2023-07-10 11:39:44.645 | silly | redis psubscribe cfg.o.enum.*
km200.0 | 2023-07-10 11:39:44.616 | silly | redis psubscribe cfg.o.system.user.*
km200.0 | 2023-07-10 11:39:44.614 | debug | Objects connected to redis: 127.0.0.1:9001
km200.0 | 2023-07-10 11:39:44.608 | debug | Objects client initialize lua scripts
km200.0 | 2023-07-10 11:39:44.564 | debug | Objects create User PubSub Client
km200.0 | 2023-07-10 11:39:44.563 | debug | Objects create System PubSub Client
km200.0 | 2023-07-10 11:39:44.562 | debug | Objects client ready ... initialize now
km200.0 | 2023-07-10 11:39:44.531 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
```

**Comment by mcm1957** [comment]
Does 2.04 work?

**In general consider migrating to adapter ems-esp.**

Not sure whether km20 will be fully adapted to js-controller 5

**Comment by mcm1957** [comment]
Info from forum:
```
INit getservices error TypeError: Cannot create property '0' on boolean 'false' at /opt/iobroker/node_modules/iobroker.km200/km200.js:455:61 at Array.forEach (<anonymous>) at /opt/iobroker/node_modules/iobroker.km200/km200.js:455:37 at /opt/iobroker/node_modules/iobroker.km200/lib/myAdapter.js:822:53
```
https://forum.iobroker.net/topic/66108/js-controller-5-0-x-jetzt-in-der-beta/390

**Comment by blackeagle998** [comment]
> Does 2.04 work?
> 
> **In general consider migrating to adapter ems-esp.**
> 
> Not sure whether km20 will be fully adapted to js-controller 5

I migrated everything to the EMS adapter. Did not know that one until today, thank you very much for that hint!

**Comment by beabel** [comment]
> In general consider migrating to adapter ems-esp.

i have also migrated to ems-esp which works with 2 modes (ems and/or km200 mode) i have both enabled and it works. the km200 adapter has not been working properly for some time. i tried updating the km200 today and i only have 1 state left. i think the best way is to close this adapter and put all power into the ems-esp.

**Comment by tp1de** [comment]
> I once picked km200 adapter because of the configurable `fast` and `slow` refresh cycles.

No need to have this within ems-esp. A full cycle for km200 with approx entities takes 20-25 seconds. 
I run with 90 secs cycle time.

**Comment by mcm1957** [comment]
Please let us and @tp1de know if ANY INCOMPATIBILITY is known or detected so that we can discuss a solution.

@tp1de I hope this is OK for you.

**Comment by tp1de** [comment]
Ich habe eine Bitte an alle die auf den EMS-ESP Adapter wechseln wollen:

Bitte liest die Readme aufmerksam durch und startet den Adapter erst einmal ohne weitere Funktionen. 
Die Summe der Fragen überfordert mich im Moment.

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
