### ISSUE TITLE
❓ Get all values

### ISSUE THREAD

**Issue by EvilEls** [iobroker-community-adapters/ioBroker.km200#28]
I got a heat pump that uses different objects than fossils-burner ;)
I cannot tell where those objects are stored, but they have to be there since the Bosch web application somehow gets them.
Is there a way to pull ALL available values at once? Or do you have to address each property one by one?
How could I find heat pump specific objects?

**Comment by mcm1957** [comment]
outdated

Please open a new request if still some interest here or at ioboer.adapter-requests.
