### ISSUE TITLE
No more seperate heating circuits

### ISSUE THREAD

**Issue by Breiti66** [iobroker-community-adapters/ioBroker.km200#30]
since a while my seperate heating circuits disapeared.
before I had 3 seperate circurits with all data.
Buderus GB142; Buderus Logamatic R4121; MEC 2; FM442; KM200

**Comment by mcm1957** [comment]
Please indicate if this issue still exists with latest version (2.0.5)

Please add all related versions
adapter version:
admin version:
js-controller version:
node version:
operating system and version:

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
