### ISSUE TITLE
Just a small hint :-) please update your docu

### ISSUE THREAD

**Issue by worksasdesigned** [iobroker-community-adapters/ioBroker.km200#35]
In the meantime Bosch and Junkers provide a EasyControl app. - Which doesn't request a Benutzerpasswort.
Buderus renamed their app to Buderus MyDevice. There you can connect your Km200 or Bosch MBLANi and a Benutzerpasswort is requested.

THIS Password combined with the device PW (16 digit) works in the 64 byte string generator, and makes the IOBroker Adapter run.

Took me a few hours to figure out that the BOSCH ID Password is not the requested one, as the BOSCH / Junker Apps do not any longer request a User- Passowrd

**Comment by macpo** [comment]
This hint is important for all which have a km200 with rc35 as this combination is not supported by EasyControl and the homepage of Buderus. As I just want some temperatures as statistics it works fine.

**Comment by pingou100** [comment]
hi,

I am actually stuck at the same level. I can't figure out how to create the access key / hex string based on the user password and the device password (16 digits). Can you please explain : 

- how do i need to combine both passwords ? (e.g. Do i need a separator in between ?)
- how do i convert the combined password into an Hex String if this step is required ?

thanks!

**Comment by mcm1957** [comment]
Currently there is no further development for this adapter planned. Please migrate to ioBroker.ems-esp adapter which is maintained. If you miss any features at ioBroker.ems-esp open an issue at that repository (https://github.com/tp1de/ioBroker.ems-esp/issues).

IoBroker.km200 will stay available for some time, but keep in mind, that it will not be adapted to node 20 and upcoming js-controller v5.
