### ISSUE TITLE
Update stable version in repo to 2.0.3

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.km200#36]
# Think about update stable version to 2.0.3
**Version**: stable=**1.1.6** (834 days old) => latest=**2.0.3** (333 days old)
**Installs**: stable=**184** (45.32%), latest=**203** (50%), total=**406**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L577)

**Comment by mcm1957** [comment]
obsolete
