### ISSUE TITLE
switch to always summer mode

### ISSUE THREAD

**Issue by Bastler173** [iobroker-community-adapters/ioBroker.km200#41]
In the adapter there are two states regarding summer/ winter mode
     heatingCircuits.hc1.currentSuWiMode         (0:off;1:forced;2:cooling) read only
     heatingCircuits.hc1.suWiSwitchMode          (0:off;1:automatic;2:forced)

The first state shows the current state of the heating, whereas the second state controls if the summer/ winter mode switch is off, automatic or forced.

In spring I switch the mode directly at the heating in our basement to always summer mode so that it won't run during the nights if the temperature falls below the suwi threshold and in fall back to automatic.

Is there a way to switch the heating to summer or winter mode with the km200 adapter so that I won't have to do it at the heating in our basement?

**Comment by tim4849** [comment]
Hello together
heatingCircuits.hc1.currentSuWiMode shows always forced(1). Seems to be a bug, can you please check/correct this issue?
Thanks in advance!

**Comment by tglynx** [comment]
Hi, 

to turn a heating circuit off (hc1 as an example) first set km200.0.heatingCircuits.hc1.operationMode to manual(1).
After that, please restart the km200 adapter.
A brand new state gets created called km200.0.heatingCircuits.hc1.temperatureRoomSetpoint (not to be mistaken by km200.0.heatingCircuits.hc1.temporaryRoomSetpoint) ... 

Edit the properties of this state to min: 0 !

Set the state to 0 ... hc1 will be -> CurrentSuWiMode 0:off on the next refresh!

3 issues here with the km200 adapter:
first: km200.0.heatingCircuits.hc1.temperatureRoomSetpoint is only created when km200.0.heatingCircuits.hc1.operationMode is set to manual(1)
second: range of km200.0.heatingCircuits.hc1.temperatureRoomSetpoint should be 0 and 5 to 30
third: range of km200.0.heatingCircuits.hc1.temporaryRoomSetpoint should be -1 to 0 and 5 to 30

Michael

**Comment by tglynx** [comment]
Hi, 

only some additional info regarding km200.0.heatingCircuits.hc1.temperatureRoomSetpoint and km200.0.heatingCircuits.hc1.temporaryRoomSetpoint   ...

in km200.0.heatingCircuits.hc1.operationMode = manual(1) km200.0.heatingCircuits.hc1.temperatureRoomSetpoint = 0 turns the heating circuit off permanently
in km200.0.heatingCircuits.hc1.operationMode = auto(0) km200.0.heatingCircuits.hc1.temporaryRoomSetpoint = 0 turns the heating circuit off until the next programmed change in automatic mode while km200.0.heatingCircuits.hc1.temporaryRoomSetpoint = -1 sets the system back to the programmed automatic state (auto).

would be happy if the adapter would be updated according this info.

Current workaround is to set the heating circuits to manual and restart the adapter for the temperatureRoomSetpoint states to be created. After that temperatureRoomSetpoint and temporaryRoomSetpoint need to be edited to accept -1 and 0 value.

Regards,
Michael

**Comment by mcm1957** [comment]
Currently there is no further development for this adapter planned. Please migrate to ioBroker.ems-esp adapter which is maintained. If you miss any features at ioBroker.ems-esp open an issue at that repository (https://github.com/tp1de/ioBroker.ems-esp/issues).

IoBroker.km200 will stay available for some time, but keep in mind, that it will not be adapted to node 20 and upcoming js-controller v5.
