### ISSUE TITLE
Getting SyntaxError: Unexpected token � in JSON

### ISSUE THREAD

**Issue by RobseFr** [iobroker-community-adapters/ioBroker.km200#44]
Node.js v12.18.3
NPM 6.14.6

Logfile:
km200.0 | 2020-09-30 18:46:37.737 | info | (197904) debug: ChangeState ack:true of system = {error: SyntaxError: Unexpected token � in JSON at position 0at JSON.parse (<anonymous>)at Function.J (/opt/iobroker/node_modules/@frankjoke/myadapter
-- | -- | -- | --

Object Content:
{error: SyntaxError: Unexpected token  in JSON at position 0at JSON.parse (<anonymous>)at Function.J (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:413:24)at /opt/iobroker/node_modules/iobroker.km200/km200.js:277:31at processTicksAndRejections (internal/process/task_queues.js:97:5),error_description: 'SyntaxError: Unexpected token \u0001 in JSON at position 0 on string \u0001\u001d.\n' +"�����^'ҁ��Y�����M����q\b\b�T���2߰b�����T��;\u0013�)\u0002\u001c�E��������|v\u0007i\u0010*ۗ:۬�,�nh����I�a\\�+�o�'BH���o�\u0010�\u000f\u001eT���[�QZע���.\u0005\u0019�����g",valIs: 'value'}

More:
{error: SyntaxError: Unexpected token  in JSON at position 0at JSON.parse (<anonymous>)at Function.J (/opt/iobroker/node_modules/@frankjoke/myadapter/myAdapter.js:413:24)at /opt/iobroker/node_modules/iobroker.km200/km200.js:277:31at processTicksAndRejections (internal/process/task_queues.js:97:5),error_description: `SyntaxError: Unexpected token \u001d in JSON at position 0 on string \u001d�ϗ2\u0019ṗ�:�ç%�����\u001b��Yb�M���\u0018���2߰b�����T��;团�i��ދ\u0005������N��XN����Y��s.1|����I�a\\�+�o�'BH���ή�\u001d\fEw��zM|�\u001e���)\u000bv��'F��aE�|�d��E\u001d��.Y�\u0001u���\u0004��"�$GP*94�\u000e����I�a\\�+�o�'BH���ή�\u001d\fEw��zM|�7�s1@���@�\u0013o\u0001�\u0012m�[AZ�H��+��W[��\u00059]V����%vO��E���ˉ�t�_\u00196�q�)�\u000f\u0017�E��.��q\u0003�&\b�ybQ�\u001f�k�{Жֹ�ʾȅ�N_�TPøzJ_�?\td'\r"7�xMͲ�\u0011��\u0010L�ܸQ\n` +'r�\n' +'��tG����\u000b#�/�QZK�[Ot/RS��\u0014�\u0014�����8\f�`BO�]{ƛ\u0000�\f���\u0004r��̙�V}\'��\u0001\t� c\'�ywU���0ꏥ�;쮓��\u0000����Qn��Q\u0015��H~�,9�CԔ�+��Iђ�\\�\u0014\u0018�\f�痾�\f�%�1;�eL\u0013��b���Yi�"��C~A��Ⱥ}I\r�;V���vDE�|�d��E\u001d��.Y�\u0001u�\u0012Tb�ML#����\u001c�\t�O\u000b;��\u0006U�A$ˡC�Ö�\u0016�k�E���羵��H2���Ǩ��^�؃b���\u0017���Ylih�\u0015_��s�l�W|չ�\u0015�~��%Wm78�z@����S?4��n\u0005m\t?+�����-\u001f�Ǳ\u0003���\n' +'s�C��1kF\u0019\u0013\u0018�RE��.��q\u0003�&\b�ybQ�3�<�<\u001e3(\u0013\u001e�\t\u000b��N����\u0004�\u0016��\u00191<a\u000b����)����4(�\u0018s����<�\u0007N�g��\u001b!\u000fn���N-��0V�$Y&����[{���)3�BD�,��zw�\u0006\u0004ZM8�48V��\u000e�\u00164!�\u001e�#��sۮ�l�L\u0001V����0ꏥ�;쮓��\u0000�~�\u000f��jh� v���-P�CԔ�+��Iђ�\\�\u0014\u0018�\f�痾�\f�%�1;�eL�Ɖ���\u001a~<�.�\bi�n��Ⱥ}I\r�;V���vDE�|�d��E\u001d��.Y�\u0001u��C��?.�_�0���\u0018\u0014rY��`p��B\f�h�R\f�O�-��H{�tJ��ᾠ�WV��0\f��\tۥU��@O�ӾNO���\u000bSn�F|�dC_�Į��L��\u0014P��&���0ꏥ�;쮓��\u0000��\u000eg(�|󪮹q5�i��ה)[)���\u0001��o�L�����m�\u0002?�;�x��?\u000f��\u0017\b��s�\b�,�\t\u0010Ђ]�#����\u001d6��&�Xh\u0011�w(�9?���%L_6��rK�\u001e=�6s\\�\u0001v�PB�\u0016�k�E���羵��H2���Ǩ��^�؃b��\u0000�y�!Q�\u0014�w�L��f�<�\u0017c�\u00074\u0015�\u001d5C�}�#Znʹ͕8���&Š�\u0014Y�@�-�\\}q��\\�\u0014�F\r�H���%.=ju�)�dȿ¶�\u001e=H��6��*]\u00105�G<(\u0019����\u001c@�s�N�\u0002�a�W:�B�\u0016���\u0010<�*��\\5��B���i�N\u0006r\u000f�C%U�c�;\u0018擄�6���s4Oa�x�M�ž\u001c ���\u0014��j�a\u0000��M�\u000f�\u0005���\u0010īCF�;�78�z@����S?4��n\u0005/z�B�b��|\u0004���\u001b:�{�N�O��$Jxu��RJo��6���s4Oa�x�M���9\u0006�����\u001aлN\u0004�\u0007�`�@W9�ٓDe4E��`�N�\u0002�a�W:�B�\u0016����1f��c�\u0002Kj�P\u001b������X;�%H\b�>9����6���s4Oa�x�M��ŪL���\u0004�߸�"��s\u001c(gg\'f�=͓����g78�z@����S?4��n\u0005x_��⃌\u001f�ֵg��\t\\�OJttZ8��!�b�ߍ8%xcli�`�\u000e\u0005��ubd��\u0012�]�0#Ǻ�7ĕ�{�Q\rs\u001a��ʵ)���J�~υ�\u00067�+v9j���\u001b��N�\u0002�a�W:�B�\u0016���\u0018u0��\u0001��EN�j5#�\u0006�?\u0014�1\u0015�\u001d���\u0013\u001f\u0007g_\u000e\bDbF5\u001e$;�s8����X �?\u001a̽j�C!ou�E`Fg�\u0006����rw{�\u0003Sxt��[��+?\b�T�\u000b\r��V&i8<�0\u001dą�\u0006d�0��D�����\u00141���ZȲ�x�����2�E��v�븜O�-��H{�tJ��ᾠ�WV��0\f��\tۥU��@O\u001f��T�8��1{x:2�e�jQ��\u0000��b��B�\u001cL�\'�\u001f�ӱ��[>���W\u0016\u0002`�c��k\u0003�����AQ%F\r�H���%.=ju�)�dȿ¶�\u001e=H��6��*]\r��G\u001c\u001b���#��5~M�r�uu\u0018.  �Y\u0006�(|Za:l������C\u0014`�yZ\u0001rY��`p��B\f�h�R\f�O�-��H{�tJ��ᾠ�WV��0\f��\tۥU��@OK0��TB�ݠ��O�N��+���Ӱ4�5u��`���\u0013K�\rx�8CJ)�q\u0012\u000f�\u0013��\u000f��\u0005�?�$�\b\t(�JF�`#o�܈��\u0001�\\�7\u001e�\n' +'\u001c�\u0012�i�ʵ\u001a���j\u001f\u0001L��~绾Ѩ��\u0012�\u0005X\u0015?5ru7h��+����5�g�.<\u0013Ek�\b�E��.��q\u0003�&\b�ybQ�tz�w�D��$I:��k;4\u0014α\u001b^���\u001b6˅H3F#E�|�d��E\u001d��.Y�\u0001u��\u0017�\fɀ\u001d��\u0002�n����\u0016�k�E���羵��H2���Ǩ��^�؃b��П����3i�q�5A�\u000fB78�z@����S?4��n\u0005��T�J�0-��J\u0014b*9\u0017\u0019Z9j\u001e����\u0010h�e�\u001d\u0002\t(�JF�`#o�܈��\u0001ӷ\u0005�\f \u0004��,��/o��*�{���*�q\u001b��R\u0006��"7�xMͲ�\u0011��\u0010L��\u0005\u0005�.ʬ\u0012:�\u001d\u0015\u000f�;��F\r�H���%.=ju�)�dȿ¶�\u001e=H��6��*]�\u0013�-$���B\u0015|K�uZ��.@_\u000b\u0007+�J�;5\\�}����I�a\\�+�o�\'BH���ή�\u001d\fEw��zM|��D�nd�\u0002>��~@���\u0007֣^�\u0000?����N\u0011�!�|�\u0015���/�������t�\t(�JF�`#o�܈��\u0001�ѽ/{����J�0���էr�uu\u0018.  �Y\u0006�(|Za�\u000f��\u0011Z��&\'�Rs�A�&N�\u001dSE��4�`�i?��F\u001e[��\u0016���\'����?<S\r\u0016��r!\u0015\u0016Wp6�E���P�,�q\u0015�����*g\u0018�\u000b�=a�Y6\u0011�[ʤg�\u001f{���)3�BD�,��zw�c\u001c��9�?��Lsj�Z�\u0007������5�۟}��R˙��\u0006\u000b;\u0002\u001d��Սc�S�Awd��[��\u0004D(�S^�m\u0014F\r�H���%.=ju�)�dȿ¶�\u001e=H��6��*]�]�t=��y<��׾)\u0018',valIs: 'value'}

**Comment by RobseFr** [comment]
Got it, you just need to add mcrypt at the javascript adapter!!! arg...

**Comment by Okrim1974** [comment]
Hi there,

I have the same problem and get a syntax error.

How did you add mcrypt to iobroker? I do not understand that. What exactly do I have to do?

**Comment by Okrim1974** [comment]
Here's an example:
{
  "common": {
    "name": "dhwCircuits",
    "read": true,
    "write": false,
    "state": "state",
    "role": "value",
    "type": "string",
    "unit": ""
  },
  "type": "state",
  "_id": "km200.0.dhwCircuits",
  "native": {
    "km200": {
      "error": {},
      "error_description": "SyntaxError: Unexpected token u in JSON at position 1 on string 4u��B�~�A�aB/\u001f9�0\u0010�v��MU9���\u0002��Y��9�y\u001e\u000b9�\u000f\u000bg�\r!}\"8�Ȟ�1�u&���W��ne.݉<��!��3��'���9Ɔ>\u001d1��M�V8h�!���=���1 0Pq\u0006�S�XuO=��#f\n",
      "valIs": "values"
    }
  },
  "from": "system.adapter.km200.0",
  "user": "system.user.admin",
  "ts": 1639753682322,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Matzeonom** [comment]
Hi...
might be a bit late, but maybe it helps others, as I had the same above issue.
In my case it was a special character (_) in the passwort of the app....
Took me days, but finally, it works !!!!!
Yessssssssss

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
