### ISSUE TITLE
adapter.objects.getObjectList is deprecated

### ISSUE THREAD

**Issue by allmyjoes** [iobroker-community-adapters/ioBroker.km200#52]
ioBroker Log is reporting: "(22598) adapter.objects.getObjectList is deprecated, and will be removed in the future. Please use adapter.getObjectList/Async. Report this to Developer!"

Maybe you have to change here something

**Comment by t2aBerlin** [comment]
same here, I can't see any objects

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
