### ISSUE TITLE
Servicemeldungen im Klartext anzeigen

### ISSUE THREAD

**Issue by FreunderNacht** [iobroker-community-adapters/ioBroker.km200#53]
Hallo,
ist es möglich das die anstehenden Servicemeldungen als Klartext in den Objekten angezeigt werden können?

Bei mir sieht es aktuell so aus:

![Anzeige des Textes der Servicemeldung](https://user-images.githubusercontent.com/69077006/106782471-7d41a800-664a-11eb-907f-fbc7c84851fa.jpg)

Oder muss ich noch Einstellungen anpassen?

![KM200 Adaptereinstellungen](https://user-images.githubusercontent.com/69077006/106782926-0822a280-664b-11eb-905a-29a2929e01d1.jpg)

Danke
Gruß´

Freund der Nacht

**Comment by beabel** [comment]
i Have a SQL DB with german Error Text.
maybe you can create a script that read from DB and show inside IObroker.
[fehlercodes.zip](https://github.com/frankjoke/ioBroker.km200/files/7253688/fehlercodes.zip)

**Comment by mcm1957** [comment]
related to #80

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
