### ISSUE TITLE
Integrierung - Buderus KM200 HRV für Lüftungsanlagen

### ISSUE THREAD

**Issue by mbhomie007** [iobroker-community-adapters/ioBroker.km200#54]
Hallo @frankjoke 
Ich habe folgenden Request.
Vielleicht könnte dies integriert werden.

Ich benutze die Adapter Version 2.0.3.

Leider ist in dem Adapter das Buderus KM200 HRV Gateway für Logavent Lüftungsanlagen nicht integriert.

Die Daten lassen sich nicht richtig auslesen, einige Daten werden aber abgegriffen.
Die Verbindung wurde erfolgreich über den Adapter hergestellt.
Nur kann man mit den Daten nichts anfangen...

![Unbenannt](https://user-images.githubusercontent.com/64688879/107031444-7a61c700-67b2-11eb-8383-2d1745a132f4.JPG)

Habe eine Buderus HRV2 Lüftungsanlage in Verbindung mit dem KM200 HRV und der Buderus App "My Vent".

Produkt:
https://www.buderus.de/de/produkte/catalogue/alle-produkte/7719_gateway-logamatic-web-km100-km200-km200-hrv

Ich bin gerne bereit bei der Integrierung zu unterstützen und zu testen.

**Comment by mbhomie007** [comment]
@frankjoke 

Wird noch an dem Adapter gearbeitet?
Bitte um kurze Rückmeldung.

**Comment by mbhomie007** [comment]
An dem Adapter wird leider schon lange nicht mehr gearbeitet.

Stattdessen bin ich mit dem Adapter voll zufrieden.

Auch die Lüftungsanlage ist integriert.

https://github.com/tp1de/ioBroker.ems-esp

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
