### ISSUE TITLE
State value to set for "xxxx" has to be type "string" but received type "object"

### ISSUE THREAD

**Issue by quorle** [iobroker-community-adapters/ioBroker.km200#58]
Bitte Adapter für Admin 5 vorbereiten und States abändern.

LOG:
`

km200.0 | 2021-05-05 00:10:05.379 | info | (16720) Adapter km200 initialization finished with 122 states.
-- | -- | -- | --
km200.0 | 2021-05-05 00:09:34.236 | info | (16720) Slow Interval=6 hours, Slow-List: recordings.dhwCircuits.dhw1.actualTemp._Days,recordings.dhwCircuits.dhw1.actualTemp._Months,recordings.heatSources.actualCHPower._Days,recordings.heatSources.
km200.0 | 2021-05-05 00:09:34.236 | info | (16720) Fast Interval=2 min, Fast-List: dhwCircuits.dhw1.actualTemp,heatSources.actualModulation,heatSources.actualPower,heatSources.actualSupplyTemperature,heatSources.applianceSupplyTemperature,heat
km200.0 | 2021-05-05 00:09:34.236 | info | (16720) Interval=25 min, Norm-list: dhwCircuits.dhw1.charge,dhwCircuits.dhw1.chargeDuration,dhwCircuits.dhw1.currentSetpoint,dhwCircuits.dhw1.holidayMode.activated,dhwCircuits.dhw1.operationMode,dhwCi
km200.0 | 2021-05-05 00:09:34.230 | info | (16720) KM200 found 122 states, get their values now.
km200.0 | 2021-05-05 00:09:30.319 | warn | (16720) State value to set for "km200.0.heatingCircuits.hc1.temporaryRoomSetpoint" has value "-1" less than min "5"
km200.0 | 2021-05-05 00:09:30.276 | warn | (16720) State value to set for "km200.0.heatingCircuits.hc1.temporaryRoomSetpoint" has value "-1" less than min "5"
km200.0 | 2021-05-05 00:09:29.443 | warn | (16720) State value to set for "km200.0.heatingCircuits.hc1.fastHeatupFactor" has value "0" less than min "1"
km200.0 | 2021-05-05 00:09:29.400 | warn | (16720) State value to set for "km200.0.heatingCircuits.hc1.fastHeatupFactor" has value "0" less than min "1"
km200.0 | 2021-05-05 00:09:26.021 | info | (16720) Services found: 127
km200.0 | 2021-05-05 00:08:36.972 | info | (16720) km200.0 address: http://192.168..........
km200.0 | 2021-05-05 00:08:36.970 | info | (16720) km200 initialization started...
km200.0 | 2021-05-05 00:08:36.967 | info | (16720) debug: km200 received undefined objects and 122 states, with config adresse,blacklist,fastlist,slowlist,interval,fastinterval,slowinterval,deletestates,accesskey,privatepassword,lang,latitude,
km200.0 | 2021-05-05 00:08:36.789 | info | (16720) starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.km200, node: v12.22.1, js-controller: 3.3.8
km200.0 | 2021-05-05 00:08:32.862 | warn | (3310) Adapter will exit in latest 1 sec with code false!
km200.0 | 2021-05-05 00:08:32.861 | info | (3310) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
km200.0 | 2021-05-05 00:08:32.861 | info | (3310) terminating
km200.0 | 2021-05-05 00:08:32.858 | info | (3310) Adapter disconnected and stopped with dostop(false) and callback(true)
km200.0 | 2021-05-05 00:08:32.857 | info | (3310) Got terminate signal TERMINATE_YOURSELF
km200.0 | 2021-05-05 00:04:42.541 | info | (3310) State value to set for "km200.0.recordings.system.sensors.temperatures.outdoor_t1._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:42.540 | info | (3310) State value to set for "km200.0.recordings.system.sensors.temperatures.outdoor_t1._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:41.961 | info | (3310) State value to set for "km200.0.recordings.system.heatSources.hs1.actualPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:41.960 | info | (3310) State value to set for "km200.0.recordings.system.heatSources.hs1.actualPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:41.380 | info | (3310) State value to set for "km200.0.recordings.heatingCircuits.hc1.roomtemperature._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:41.380 | info | (3310) State value to set for "km200.0.recordings.heatingCircuits.hc1.roomtemperature._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:40.798 | info | (3310) State value to set for "km200.0.recordings.heatSources.hs1.actualPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:40.797 | info | (3310) State value to set for "km200.0.recordings.heatSources.hs1.actualPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:40.250 | info | (3310) State value to set for "km200.0.recordings.heatSources.actualPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:40.250 | info | (3310) State value to set for "km200.0.recordings.heatSources.actualPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:39.640 | info | (3310) State value to set for "km200.0.recordings.heatSources.actualDHWPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:39.640 | info | (3310) State value to set for "km200.0.recordings.heatSources.actualDHWPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:39.102 | info | (3310) State value to set for "km200.0.recordings.heatSources.actualCHPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:39.102 | info | (3310) State value to set for "km200.0.recordings.heatSources.actualCHPower._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:37.866 | info | (3310) State value to set for "km200.0.recordings.dhwCircuits.dhw1.actualTemp._Hours" has to be type "string" but received type "object"
km200.0 | 2021-05-05 00:04:37.850 | info | (3310) State value to set for "km200.0.recordings.dhwCircuits.dhw1.actualTemp._Hours" has to be type "string" but received type "object"

`

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
