### ISSUE TITLE
Bitte um Hilfe bei der Einrichtung des Adapters

### ISSUE THREAD

**Issue by Fischer201290** [iobroker-community-adapters/ioBroker.km200#62]
<html>
<body>

km200.0 | PID | Zeit | debug | Nachricht
-- | -- | -- | -- | --
km200.0 | 5298 | 2021-08-05 14:51:43.960 | info | Adapter km200 initialization finished with 0 states.
km200.0 | 5298 | 2021-08-05 14:51:43.947 | info | Slow Interval=6 hours, Slow-List:
km200.0 | 5298 | 2021-08-05 14:51:43.946 | info | Fast Interval=2 min, Fast-List:
km200.0 | 5298 | 2021-08-05 14:51:43.946 | info | Interval=1 min, Norm-list:
km200.0 | 5298 | 2021-08-05 14:51:43.944 | info | KM200 found 0 states, get their values now.
km200.0 | 5298 | 2021-08-05 14:51:43.943 | info | Services found: 41
km200.0 | 5298 | 2021-08-05 14:51:43.942 | warn | Did not get any Services from KLM200!: {}
km200.0 | 5298 | 2021-08-05 14:51:43.920 | warn | Skip service data of /system
km200.0 | 5298 | 2021-08-05 14:51:18.770 | warn | Skip service data of /solarCircuits
km200.0 | 5298 | 2021-08-05 14:50:53.619 | warn | Skip service data of /recordings
km200.0 | 5298 | 2021-08-05 14:50:28.467 | warn | Skip service data of /notifications
km200.0 | 5298 | 2021-08-05 14:50:03.315 | warn | Skip service data of /heatSources
km200.0 | 5298 | 2021-08-05 14:49:38.162 | warn | Skip service data of /heatingCircuits
km200.0 | 5298 | 2021-08-05 14:49:13.009 | warn | Skip service data of /gateway
km200.0 | 5298 | 2021-08-05 14:48:47.852 | warn | Skip service data of /dhwCircuits
km200.0 | 5298 | 2021-08-05 14:48:22.701 | info | km200.0 address: http://194.168.178.185:80
km200.0 | 5298 | 2021-08-05 14:48:22.699 | info | km200 initialization started...
km200.0 | 5298 | 2021-08-05 14:48:22.591 | info | starting. Version 2.0.3 in /opt/iobroker/node_modules/iobroker.km200, node: v12.22.4, js-controller: 3.3.15

</body>
</html>

Hallo,

oben aufgelistete Meldungen kommen bei mir im ioBroker.
In den Objekten taucht der Ordner auf, ist allerdings leer bis auf ein admin Ordner, der aber auch leer ist.

**Comment by Borilu** [comment]
Ich habe das gleiche Problem. In den Objekten finden sich nur leere Ordner.

**Comment by StefanParli** [comment]
Bei mir sieht es genauso aus.
Ich habe ein MB LAN 2

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
