### ISSUE TITLE
Warum funktioniert der Adapter bei mir nicht mehr?

### ISSUE THREAD

**Issue by oe8bck** [iobroker-community-adapters/ioBroker.km200#67]
Hallo,

Erstmals vielen Dank für den Adapter! Ich hatte den in meiner "alten" Anlage mit einem Intel-NUC erfolgreicht im Betrieb. 

Aber nachdem ich das auf Raspi mit Docker umgestellt habe, funktioniert er nicht mehr. In der Instanzliste werden 2x grüne Häkchen angezeigt bei km200.0 in Version v2.0.3. Objekt gibt's im Baum unter km200.0 auch, aber da wird z.B: angezeigt:

```
{
  "common": {
    "name": "dhwCircuits",
    "read": true,
    "write": false,
    "state": "state",
    "role": "value",
    "type": "string",
    "unit": ""
  },
  "type": "state",
  "_id": "km200.0.dhwCircuits",
  "native": {
    "km200": {
      "error": {},
      "error_description": "SyntaxError: Unexpected token ! in JSON at position 1 on string {!R繫��.....",
      "valIs": "values"
    }
  },
  "from": "system.adapter.km200.0",
  "user": "system.user.admin",
  "ts": 1640800172377
}
```

Ich vermute mal, dass es da mit der Codepage etwas hat. Wo kann ich da mehr nachgraben?

LG,
Christof

**Comment by mcm1957** [comment]
Does the problem still exist with the latest version (2.0.5)?

Please add all related versions
adapter version:
admin version:
js-controller version:
node version:
operating system and version:

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
