### ISSUE TITLE
Request: Verbrauchsdaten auslesen

### ISSUE THREAD

**Issue by Horgul123** [iobroker-community-adapters/ioBroker.km200#79]
In der neuen App meiner Heizung sehe ich auch die verbrauchte Gasmenge. Wäre super, wenn man die auch über den Adapter auslesen könnte. Aktuell sehe ich zumindest kein Objekt dafür

**Comment by mcm1957** [comment]
Currently there is no further development for this adapter planned. Please migrate to ioBroker.ems-esp adapter which is maintained. If you miss any features at ioBroker.ems-esp open an issue at that repository (https://github.com/tp1de/ioBroker.ems-esp/issues).

IoBroker.km200 will stay available for some time, but keep in mind, that it will not be adapted to node 20 and upcoming js-controller v5.
