### ISSUE TITLE
Request: MB LAN HR

### ISSUE THREAD

**Issue by florianraimann** [iobroker-community-adapters/ioBroker.km200#82]
Die Anbindung eines MB LAN HR Gateways welches zur Steuerung einer Bosch Vent 5000C per App notwendig ist. 
MB LANi unterscheidet sich vermutlich von MB LAN HR.

**Comment by mcm1957** [comment]
Currently there is no further development for this adapter planned. Please migrate to ioBroker.ems-esp adapter which is maintained. If you miss any features at ioBroker.ems-esp open an issue at that repository (https://github.com/tp1de/ioBroker.ems-esp/issues).

IoBroker.km200 will stay available for some time, but keep in mind, that it will not be adapted to node 20 and upcoming js-controller v5.
