### ISSUE TITLE
actualPower Objekt nicht vorhanden

### ISSUE THREAD

**Issue by philipp-bender** [iobroker-community-adapters/ioBroker.km200#88]
Hallo zusammen,

gibt es eine Möglichkeit die "actualPower" auszulesen?
Ich erwarte eigentlich die Daten unter: km200.0.heatSources.hs1.actualPower.

Aufgelistet werden lediglich: 
km200.0.heatSources.hs1.actualModulation
km200.0.heatSources.hs1.flameStatus
km200.0.heatSources.hs1.info
km200.0.heatSources.hs1.type

Die Blacklist ist folgendermaßen konfiguriert:
/gateway*, *.switchPrograms.*, *.holidayModes.*, /recordings/*

Fast Refresh (1min):
*.actualTemp$, *.actualPower$, *.pumpModulation$, roomtemperature$, actualModulation$, ^notifications$, *_t1$

 Ich bin für jeden Tipp dankbar.

Viele Grüße
Philipp

**Comment by mcm1957** [comment]
Please add all related versions
adapter version:
admin version:
js-controller version:
node version:
operating system and version:

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
