### ISSUE TITLE
not valid json

### ISSUE THREAD

**Issue by cyberoner1** [iobroker-community-adapters/ioBroker.km200#89]
Hallo, habe den Adapter in der Version 2.03 installiert, bekomme aber folgenden Fehler

` "type": "state",
  "_id": "km200.0.dhwCircuits",
  "native": {
    "km200": {
      "error": {},
      "error_description": "SyntaxError: Unexpected token ']', \"]U�4�ׇ?\u0006\u0000U\"... is not valid JSON on string ]U�4�ׇ?\u0006\u0000U*\u000e7\u000e��$�\u0006_N\u0019a�D��(���R��`�<\u0019��ļ�tY6\u0010ې�\u001d\u0007���і���\u0010�ܜ8oO\u0004ǝȚ\u0018�g���#�\u0000=b>�\u000b�\u001a��y��N{���\u0012d��\u0003�E��O��<��;�]��\u0015��",
      "valIs": "values"
    }`

eine Idee dazu?

**Comment by mcm1957** [comment]
Please indicate if this issue still exists with latest version (2.0.5)

If yes, please indicate when this erro occures and where this message is logged. Add log with level debug if appropiate.

In addition please add all reletd versions
adapter version:
admin version:
js-controller version:
node version:
operating system and version:

**Comment by mcm1957** [comment]
Adapter km200 is deprected.
So this isse will be closed.

See #122
